mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - org.barino3d.mongock.changelog
spring:
  data:
    mongodb:
      uri: mongodb+srv://test:${mongo_password}@apps.16whc.mongodb.net/commands-repository?retryWrites=true&w=majority
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: commandsrepository@gmail.com
    password: ${mail_password}
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
